# OpenNVR — top-level developer / operator make targets.
#
# Security-relevant targets live here so a fresh clone can be bootstrapped
# with one command and no plaintext secrets ever land in the repo. See
# docs/SECURITY_ARCHITECTURE.md for the mapping between these targets and
# the offline-first architecture described in Zenodo 10.5281/zenodo.17261761.

PY ?= python3

.PHONY: help secrets secrets-env check-secrets

help:
	@echo "OpenNVR Makefile targets:"
	@echo "  make secrets        Print cryptographically random values for the"
	@echo "                      required secret env vars. Pipe into your .env."
	@echo "  make secrets-env    Write the random values directly to server/.env"
	@echo "                      (refuses to clobber an existing file)."
	@echo "  make check-secrets  Verify your server/.env has no placeholder"
	@echo "                      values left for the required secrets."

# --------------------------------------------------------------------------
# make secrets
# --------------------------------------------------------------------------
# Emits a ready-to-paste block of env vars with cryptographically random
# values for every secret the startup validators require. Aligned with
# V-002 in the security review and Zenodo 17261761 §4.1 (Secure-by-Design
# defaults).
#
# Usage:
#   make secrets                  # print to stdout
#   make secrets >> server/.env   # append to your env file
secrets:
	@$(PY) -c "import secrets; \
from cryptography.fernet import Fernet; \
print('# --- generated by `make secrets` ---'); \
print(f'SECRET_KEY={secrets.token_urlsafe(48)}'); \
print(f'MEDIAMTX_SECRET={secrets.token_hex(32)}'); \
print(f'INTERNAL_API_KEY={secrets.token_urlsafe(48)}'); \
print(f'CREDENTIAL_ENCRYPTION_KEY={Fernet.generate_key().decode()}'); \
print('# --- end generated block ---')"

# Convenience: write a fresh server/.env from env.example + generated secrets.
# Refuses to overwrite an existing .env so you can't accidentally rotate keys
# and lock yourself out of an existing database.
secrets-env:
	@if [ -f server/.env ]; then \
	  echo "Refusing to overwrite server/.env (already exists). Run 'make secrets >> server/.env' to append instead." >&2; \
	  exit 1; \
	fi
	@cp server/env.example server/.env
	@$(MAKE) -s secrets >> server/.env
	@echo "Wrote server/.env with random secrets. Review DATABASE_URL and any other deployment-specific values before starting."

# --------------------------------------------------------------------------
# make check-secrets
# --------------------------------------------------------------------------
# Cheap, fast linter that anyone (CI included) can run to confirm that a
# .env file is not still carrying the placeholders from env.example.
#
# H-3 reviewer finding: the placeholder fragment list MUST stay in sync with
# the runtime validator. Rather than duplicate the list here (and inevitably
# drift), we import _PLACEHOLDER_FRAGMENTS from server/core/config.py at
# runtime. A single edit to the tuple in config.py now propagates here
# automatically. Requires `server/` to be importable, which is satisfied by
# the project's normal layout — no additional install step needed.
check-secrets:
	@$(PY) -c "import os, sys; \
sys.path.insert(0, 'server'); \
from pathlib import Path; \
env = Path('server/.env'); \
sys.exit('server/.env not found') if not env.exists() else None; \
from core.secret_policy import PLACEHOLDER_FRAGMENTS; \
errs=[]; \
[errs.append(line.strip()) for line in env.read_text().splitlines() if line and not line.startswith('#') and '=' in line and any(f in line.split('=',1)[1].lower() for f in PLACEHOLDER_FRAGMENTS)]; \
print('\n'.join('  - '+e for e in errs)) if errs else None; \
sys.exit('server/.env still contains placeholder values:') if errs else print('server/.env: no placeholder values found.')"
