#!/usr/bin/env bash
# ============================================================
# OpenNVR — paper-compliant host hardening for dual-NIC deployments
# (ISSUE-6 v3, related: planned V-010/V-016/V-017)
# ============================================================
#
# Applies nftables forward-drop rules between the camera-LAN NIC and
# the operator-uplink NIC, so a compromised IP camera on the camera
# segment cannot pivot through the OpenNVR host to reach the LAN.
#
# Scope (intentionally narrow for safety):
#
#   * Adds a dedicated nft table `inet opennvr-vlan` so we never
#     touch the operator's existing firewall rules (UFW, firewalld,
#     bare iptables, fail2ban — all keep working untouched).
#   * Adds forward-chain drop rules between the two declared NICs.
#     Nothing else — no input/output rules, no DNS changes, no
#     routing changes. Those would risk locking the operator out
#     of their own box.
#   * Snapshots `nft list ruleset` and `ip route show` to
#     ./host-hardening/snapshot-<timestamp>/ BEFORE making any
#     change, so reversal is `revert-camera-vlan-hardening.sh`.
#   * Refuses to do anything without explicit consent. Printed
#     dry-run with --dry-run; actually runs only with sudo.
#
# Out of scope for this script (deferred to V-010 / V-016 / V-017):
#   * Removing the default gateway from the camera NIC (route
#     manipulation is too easy to get wrong; document it instead).
#   * Strict input filtering on the camera NIC (operator may have
#     non-camera devices on that segment legitimately during setup).
#   * DNS blackholing (depends on operator's resolver — Pi-hole,
#     AdGuard, systemd-resolved, dnsmasq all behave differently).
#
# Usage:
#   ./scripts/apply-camera-vlan-hardening.sh \
#       --camera-iface eth0 --mgmt-iface eth1 [--dry-run]
#
# Reverts with:
#   ./scripts/revert-camera-vlan-hardening.sh

set -euo pipefail

# Colours (no-op if not a TTY).
if [ -t 1 ]; then
    RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
    CYAN='\033[0;36m'; GRAY='\033[38;5;245m'; WHITE='\033[1;37m'
    NC='\033[0m'
else
    RED=''; GREEN=''; YELLOW=''; CYAN=''; GRAY=''; WHITE=''; NC=''
fi

CAMERA_IFACE=""
MGMT_IFACE=""
DRY_RUN=0

while [ $# -gt 0 ]; do
    case "$1" in
        --camera-iface) CAMERA_IFACE="$2"; shift 2 ;;
        --mgmt-iface)   MGMT_IFACE="$2";   shift 2 ;;
        --dry-run)      DRY_RUN=1;          shift   ;;
        -h|--help)
            sed -n '3,/^# Usage:/p' "$0" | sed 's/^# //;s/^#$//'
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown argument: $1${NC}" >&2
            exit 2
            ;;
    esac
done

if [ -z "$CAMERA_IFACE" ] || [ -z "$MGMT_IFACE" ]; then
    echo -e "${RED}Both --camera-iface and --mgmt-iface are required.${NC}" >&2
    echo -e "${GRAY}Example: $0 --camera-iface eth0 --mgmt-iface eth1${NC}" >&2
    exit 2
fi

if [ "$CAMERA_IFACE" = "$MGMT_IFACE" ]; then
    echo -e "${RED}Camera and uplink interfaces are the same (${CAMERA_IFACE}).${NC}" >&2
    echo -e "${RED}That defeats isolation. Aborting.${NC}" >&2
    exit 1
fi

# Sanity: do the interfaces actually exist on this host?
for iface in "$CAMERA_IFACE" "$MGMT_IFACE"; do
    if ! ip link show "$iface" >/dev/null 2>&1; then
        echo -e "${RED}Interface '${iface}' does not exist on this host.${NC}" >&2
        echo -e "${GRAY}Check spelling: ip -4 -o addr show scope global${NC}" >&2
        exit 1
    fi
done

# Refuse to run if nftables isn't available — older systems with
# only iptables would need a separate translation we haven't shipped
# yet. Don't silently fail.
if ! command -v nft >/dev/null 2>&1; then
    echo -e "${RED}nftables (nft) not installed. This script only supports nft-based hosts.${NC}" >&2
    echo -e "${GRAY}Install with: sudo apt-get install nftables (Debian/Ubuntu)${NC}" >&2
    echo -e "${GRAY}              sudo dnf install nftables (RHEL/Fedora)${NC}" >&2
    exit 1
fi

# Locate the OpenNVR project root (relative to this script).
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
# OPENNVR_HARDEN_DIR exists so the test harness can redirect the
# generated nft template + snapshot directories into a throwaway
# tmpdir without polluting the repo's host-hardening/ folder.
# Defaults to the in-repo path so operator-facing behaviour is
# unchanged.
HARDEN_DIR="${OPENNVR_HARDEN_DIR:-${PROJECT_ROOT}/host-hardening}"
TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
SNAPSHOT_DIR="${HARDEN_DIR}/snapshot-${TIMESTAMP}"
NFT_FILE="${HARDEN_DIR}/opennvr-vlan.nft"

mkdir -p "$HARDEN_DIR"

# Generate the nftables config so the operator can audit it before
# anything is applied. Plain text under host-hardening/ for review.
cat > "$NFT_FILE" <<EOF
# Generated by apply-camera-vlan-hardening.sh on $(date -Iseconds)
# Project: OpenNVR  (https://github.com/open-nvr/open-nvr)
# Scope:   Forward-drop between camera VLAN and operator uplink.
# Reverse: ./scripts/revert-camera-vlan-hardening.sh
#
# This table is intentionally isolated — adding/removing it never
# touches the host's pre-existing iptables/nftables ruleset.

table inet opennvr-vlan {
    chain forward_drop {
        # Hook into the kernel's forward path at a high (early)
        # priority so we drop before other tables can accept.
        type filter hook forward priority -150; policy accept;

        # Block IP forwarding between the camera-VLAN NIC and the
        # uplink NIC in *both* directions. A compromised camera
        # cannot pivot through the OpenNVR host to reach LAN hosts;
        # an attacker on the LAN cannot reach the cameras via the
        # OpenNVR host either.
        iifname "${CAMERA_IFACE}" oifname "${MGMT_IFACE}" log prefix "[opennvr-vlan drop cam->mgmt] " drop
        iifname "${MGMT_IFACE}" oifname "${CAMERA_IFACE}" log prefix "[opennvr-vlan drop mgmt->cam] " drop
    }
}
EOF

# Show the operator exactly what we'd run.
echo -e "${WHITE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${WHITE}OpenNVR — camera/uplink firewall isolation${NC}"
echo -e "${WHITE}Review what will run before granting sudo${NC}"
echo -e "${WHITE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${GRAY}Camera-LAN NIC : ${WHITE}${CAMERA_IFACE}${NC}"
echo -e "${GRAY}Uplink NIC     : ${WHITE}${MGMT_IFACE}${NC}"
echo -e "${GRAY}nftables file  : ${WHITE}${NFT_FILE}${NC}"
echo -e "${GRAY}Snapshot dir   : ${WHITE}${SNAPSHOT_DIR}${NC}"
echo ""
echo -e "${WHITE}Generated nftables config:${NC}"
echo -e "${GRAY}────────────────────────────────────────────${NC}"
sed 's/^/  /' "$NFT_FILE"
echo -e "${GRAY}────────────────────────────────────────────${NC}"
echo ""
echo -e "${WHITE}Commands that will run:${NC}"
echo -e "  ${CYAN}# Snapshot existing state (no privileges needed)${NC}"
echo -e "  ${CYAN}sudo nft list ruleset > ${SNAPSHOT_DIR}/nft-ruleset.before${NC}"
echo -e "  ${CYAN}ip route show > ${SNAPSHOT_DIR}/ip-route.before${NC}"
echo -e "  ${CYAN}ip -4 -o addr show > ${SNAPSHOT_DIR}/ip-addr.before${NC}"
echo -e "  ${CYAN}# Apply the rules (requires sudo)${NC}"
echo -e "  ${CYAN}sudo nft -f ${NFT_FILE}${NC}"
echo -e "  ${CYAN}# Verify${NC}"
echo -e "  ${CYAN}sudo nft list table inet opennvr-vlan${NC}"
echo ""

if [ "$DRY_RUN" -eq 1 ]; then
    echo -e "${YELLOW}Dry-run requested. Nothing applied. Exiting.${NC}"
    exit 0
fi

# Final confirmation.
read -rp "  Apply now? You'll be prompted for sudo. [y/N]: " confirm
if ! [[ "$confirm" =~ ^[Yy]$ ]]; then
    echo -e "${YELLOW}Aborted. Nothing applied.${NC}"
    exit 0
fi

# Snapshot first (no privileges yet — easy bail-out point).
mkdir -p "$SNAPSHOT_DIR"
ip route show               > "${SNAPSHOT_DIR}/ip-route.before"   2>/dev/null || true
ip -4 -o addr show          > "${SNAPSHOT_DIR}/ip-addr.before"    2>/dev/null || true
echo "$CAMERA_IFACE"        > "${SNAPSHOT_DIR}/camera-iface"
echo "$MGMT_IFACE"          > "${SNAPSHOT_DIR}/mgmt-iface"

# Now the sudo step — snapshot the existing nft ruleset under sudo
# (some chains are root-only) and then apply ours.
echo ""
echo -e "${WHITE}Snapshotting existing nft ruleset (sudo needed)...${NC}"
if ! sudo nft list ruleset > "${SNAPSHOT_DIR}/nft-ruleset.before" 2>/dev/null; then
    echo -e "${YELLOW}Warning: could not snapshot existing ruleset.${NC}" >&2
    echo -e "${YELLOW}         Continuing, but revert may be incomplete.${NC}" >&2
fi

echo -e "${WHITE}Applying opennvr-vlan table...${NC}"
if sudo nft -f "$NFT_FILE"; then
    echo ""
    echo -e "${GREEN}✓ Hardening applied successfully.${NC}"
    echo -e "${GRAY}  Verify   : sudo nft list table inet opennvr-vlan${NC}"
    echo -e "${GRAY}  Revert   : ${PROJECT_ROOT}/scripts/revert-camera-vlan-hardening.sh${NC}"
    echo -e "${GRAY}  Snapshot : ${SNAPSHOT_DIR}${NC}"
    # Also persist the active snapshot pointer so revert knows what
    # to undo.
    ln -sfn "$SNAPSHOT_DIR" "${HARDEN_DIR}/snapshot-active"
else
    echo -e "${RED}Apply failed. Nothing changed.${NC}" >&2
    exit 1
fi
