# Copyright (c) 2026 OpenNVR
# This file is part of OpenNVR.
# 
# OpenNVR is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# OpenNVR is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with OpenNVR.  If not, see <https://www.gnu.org/licenses/>.

"""initial_schema_squash

Revision ID: d75d15b88c1a
Revises:
Create Date: 2026-02-13 12:31:39.670200

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d75d15b88c1a"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_models",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("model_name", sa.String(length=50), nullable=False),
        sa.Column("task", sa.String(length=50), nullable=False),
        sa.Column("config", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column("assigned_camera_id", sa.Integer(), nullable=True),
        sa.Column("recording_path", sa.Text(), nullable=True),
        sa.Column("inference_interval", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_models_assigned_camera_id"),
        "ai_models",
        ["assigned_camera_id"],
        unique=False,
    )
    op.create_index(op.f("ix_ai_models_id"), "ai_models", ["id"], unique=False)
    op.create_index(
        op.f("ix_ai_models_source_type"), "ai_models", ["source_type"], unique=False
    )
    op.create_index(op.f("ix_ai_models_task"), "ai_models", ["task"], unique=False)
    op.create_table(
        "firewall_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "direction",
            sa.Enum("inbound", "outbound", name="firewalldirection"),
            nullable=False,
        ),
        sa.Column("protocol", sa.String(length=8), nullable=False),
        sa.Column("port_from", sa.Integer(), nullable=True),
        sa.Column("port_to", sa.Integer(), nullable=True),
        sa.Column("sources", sa.Text(), nullable=True),
        sa.Column(
            "action", sa.Enum("allow", "deny", name="firewallaction"), nullable=False
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("hit_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_firewall_rules_id"), "firewall_rules", ["id"], unique=False
    )
    op.create_table(
        "integrations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "WEBHOOK",
                "SLACK",
                "TEAMS",
                "EMAIL",
                "MQTT",
                "S3",
                "SYSLOG",
                "PROMETHEUS",
                name="integrationtype",
            ),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_integrations_id"), "integrations", ["id"], unique=False)
    op.create_table(
        "password_policy",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("min_length", sa.Integer(), nullable=False),
        sa.Column("min_classes", sa.Integer(), nullable=False),
        sa.Column("disallow_username_email", sa.Boolean(), nullable=False),
        sa.Column("passphrase_enabled", sa.Boolean(), nullable=False),
        sa.Column("passphrase_min_length", sa.Integer(), nullable=False),
        sa.Column("history_count", sa.Integer(), nullable=False),
        sa.Column("expiration_days", sa.Integer(), nullable=True),
        sa.Column("max_failed_attempts", sa.Integer(), nullable=False),
        sa.Column("lockout_minutes", sa.Integer(), nullable=False),
        sa.Column("reset_token_ttl_minutes", sa.Integer(), nullable=False),
        sa.Column("require_mfa_for_privileged", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_password_policy_id"), "password_policy", ["id"], unique=False
    )
    op.create_table(
        "permissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_permissions_id"), "permissions", ["id"], unique=False)
    op.create_index(op.f("ix_permissions_name"), "permissions", ["name"], unique=True)
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_roles_id"), "roles", ["id"], unique=False)
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=True)
    op.create_table(
        "security_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("json_value", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_security_settings_id"), "security_settings", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_security_settings_key"), "security_settings", ["key"], unique=True
    )
    op.create_table(
        "ai_detection_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.Column("camera_id", sa.Integer(), nullable=True),
        sa.Column("task", sa.String(length=50), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("bbox_x", sa.Integer(), nullable=True),
        sa.Column("bbox_y", sa.Integer(), nullable=True),
        sa.Column("bbox_width", sa.Integer(), nullable=True),
        sa.Column("bbox_height", sa.Integer(), nullable=True),
        sa.Column("count", sa.Integer(), nullable=True),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("annotated_image_uri", sa.Text(), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["ai_models.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_detection_results_camera_id"),
        "ai_detection_results",
        ["camera_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_detection_results_created_at"),
        "ai_detection_results",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_detection_results_id"), "ai_detection_results", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_ai_detection_results_model_id"),
        "ai_detection_results",
        ["model_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_detection_results_task"),
        "ai_detection_results",
        ["task"],
        unique=False,
    )
    op.create_table(
        "role_permissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role_id", "permission_id", name="uq_role_permission"),
    )
    op.create_index(
        op.f("ix_role_permissions_id"), "role_permissions", ["id"], unique=False
    )
    op.create_index(
        "ix_role_permissions_perm", "role_permissions", ["permission_id"], unique=False
    )
    op.create_index(
        "ix_role_permissions_role", "role_permissions", ["role_id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=True),
        sa.Column("last_name", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=True),
        sa.Column("password_set", sa.Boolean(), nullable=True),
        sa.Column("mfa_enabled", sa.Boolean(), nullable=True),
        sa.Column("encrypted_mfa_secret", sa.String(length=500), nullable=True),
        sa.Column("failed_login_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=True),
        sa.Column("entity_id", sa.String(length=128), nullable=True),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_entity_id"), "audit_logs", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_entity_type"), "audit_logs", ["entity_type"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_id"), "audit_logs", ["id"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_timestamp"), "audit_logs", ["timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False
    )
    op.create_table(
        "cameras",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=False),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column("username", sa.String(length=50), nullable=True),
        sa.Column("encrypted_password", sa.String(length=500), nullable=True),
        sa.Column("rtsp_url", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("vlan", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("manufacturer", sa.String(length=100), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("firmware_version", sa.String(length=100), nullable=True),
        sa.Column("serial_number", sa.String(length=100), nullable=True),
        sa.Column("hardware_id", sa.String(length=100), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_camera_ip", "cameras", ["ip_address"], unique=False)
    op.create_index("ix_camera_owner", "cameras", ["owner_id"], unique=False)
    op.create_index(op.f("ix_cameras_id"), "cameras", ["id"], unique=False)
    op.create_table(
        "cloud_provider_credentials",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("encrypted_token", sa.Text(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("encryption_key_id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("account_info", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "token_hash", name="uq_user_token"),
    )
    op.create_index(
        "ix_cloud_cred_user_provider",
        "cloud_provider_credentials",
        ["user_id", "provider"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cloud_provider_credentials_provider"),
        "cloud_provider_credentials",
        ["provider"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cloud_provider_credentials_token_hash"),
        "cloud_provider_credentials",
        ["token_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cloud_provider_credentials_user_id"),
        "cloud_provider_credentials",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "tenant_quotas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("daily_quota", sa.Integer(), nullable=False),
        sa.Column("monthly_quota", sa.Integer(), nullable=False),
        sa.Column("concurrent_limit", sa.Integer(), nullable=False),
        sa.Column("daily_usage", sa.Integer(), nullable=False),
        sa.Column("monthly_usage", sa.Integer(), nullable=False),
        sa.Column("concurrent_usage", sa.Integer(), nullable=False),
        sa.Column("daily_reset_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("monthly_reset_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("circuit_state", sa.String(length=20), nullable=False),
        sa.Column("circuit_failure_count", sa.Integer(), nullable=False),
        sa.Column("circuit_last_failure", sa.DateTime(timezone=True), nullable=True),
        sa.Column("circuit_half_open_successes", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "provider", name="uq_user_provider_quota"),
    )
    op.create_index(op.f("ix_tenant_quotas_id"), "tenant_quotas", ["id"], unique=False)
    op.create_table(
        "camera_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("camera_id", sa.Integer(), nullable=False),
        sa.Column("stream_protocol", sa.String(length=16), nullable=False),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("recording_enabled", sa.Boolean(), nullable=True),
        sa.Column("recording_path", sa.String(length=500), nullable=True),
        sa.Column("recording_segment_seconds", sa.Integer(), nullable=True),
        sa.Column("webrtc_publisher", sa.Boolean(), nullable=True),
        sa.Column("rtmp_publisher", sa.Boolean(), nullable=True),
        sa.Column("rtsp_transport", sa.String(length=16), nullable=True),
        sa.Column("extra_options", sa.Text(), nullable=True),
        sa.Column("last_provisioned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("proxy_enabled", sa.Boolean(), nullable=False),
        sa.Column("stream_active", sa.Boolean(), nullable=False),
        sa.Column("last_stream_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stream_failures", sa.Integer(), nullable=False),
        sa.Column("auto_restart", sa.Boolean(), nullable=False),
        sa.Column("max_restart_attempts", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["camera_id"],
            ["cameras.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("camera_id"),
    )
    op.create_index(
        op.f("ix_camera_configs_id"), "camera_configs", ["id"], unique=False
    )
    op.create_table(
        "camera_permissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("camera_id", sa.Integer(), nullable=False),
        sa.Column("can_view", sa.Boolean(), nullable=True),
        sa.Column("can_manage", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["camera_id"],
            ["cameras.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "camera_id", name="uq_user_camera_perm"),
    )
    op.create_index(
        op.f("ix_camera_permissions_camera_id"),
        "camera_permissions",
        ["camera_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_camera_permissions_id"), "camera_permissions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_camera_permissions_user_id"),
        "camera_permissions",
        ["user_id"],
        unique=False,
    )
    op.create_index("ix_perm_camera", "camera_permissions", ["camera_id"], unique=False)
    op.create_index("ix_perm_user", "camera_permissions", ["user_id"], unique=False)
    op.create_table(
        "cloud_provider_models",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("credential_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("model_id", sa.String(length=200), nullable=False),
        sa.Column("task", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("config", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["credential_id"],
            ["cloud_provider_credentials.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "model_id", name="uq_user_model_id"),
    )
    op.create_index(
        "ix_cloud_model_user_task",
        "cloud_provider_models",
        ["user_id", "task"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cloud_provider_models_id"),
        "cloud_provider_models",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cloud_provider_models_task"),
        "cloud_provider_models",
        ["task"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cloud_provider_models_user_id"),
        "cloud_provider_models",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "recordings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("file_size", sa.Float(), nullable=True),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column("recording_type", sa.String(length=50), nullable=True),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_processed", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("camera_id", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["camera_id"],
            ["cameras.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recordings_id"), "recordings", ["id"], unique=False)
    op.create_table(
        "cloud_inference_results",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("model_name", sa.String(length=200), nullable=False),
        sa.Column("task", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("result_json", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("provider_request_id", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["cloud_provider_models.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cloud_inference_results_created_at"),
        "cloud_inference_results",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cloud_inference_results_task"),
        "cloud_inference_results",
        ["task"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cloud_inference_results_user_id"),
        "cloud_inference_results",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_cloud_result_user_date",
        "cloud_inference_results",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "ai_inference_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("model_name", sa.String(length=200), nullable=False),
        sa.Column("task", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("input_json", sa.Text(), nullable=False),
        sa.Column("parameters_json", sa.Text(), nullable=True),
        sa.Column("result_id", sa.String(length=36), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["cloud_provider_models.id"],
        ),
        sa.ForeignKeyConstraint(
            ["result_id"],
            ["cloud_inference_results.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_inference_jobs_created_at"),
        "ai_inference_jobs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_inference_jobs_status"),
        "ai_inference_jobs",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_inference_jobs_user_id"),
        "ai_inference_jobs",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_job_status_created",
        "ai_inference_jobs",
        ["status", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_job_status_created", table_name="ai_inference_jobs")
    op.drop_index(op.f("ix_ai_inference_jobs_user_id"), table_name="ai_inference_jobs")
    op.drop_index(op.f("ix_ai_inference_jobs_status"), table_name="ai_inference_jobs")
    op.drop_index(
        op.f("ix_ai_inference_jobs_created_at"), table_name="ai_inference_jobs"
    )
    op.drop_table("ai_inference_jobs")
    op.drop_index("ix_cloud_result_user_date", table_name="cloud_inference_results")
    op.drop_index(
        op.f("ix_cloud_inference_results_user_id"), table_name="cloud_inference_results"
    )
    op.drop_index(
        op.f("ix_cloud_inference_results_task"), table_name="cloud_inference_results"
    )
    op.drop_index(
        op.f("ix_cloud_inference_results_created_at"),
        table_name="cloud_inference_results",
    )
    op.drop_table("cloud_inference_results")
    op.drop_index(op.f("ix_recordings_id"), table_name="recordings")
    op.drop_table("recordings")
    op.drop_index(
        op.f("ix_cloud_provider_models_user_id"), table_name="cloud_provider_models"
    )
    op.drop_index(
        op.f("ix_cloud_provider_models_task"), table_name="cloud_provider_models"
    )
    op.drop_index(
        op.f("ix_cloud_provider_models_id"), table_name="cloud_provider_models"
    )
    op.drop_index("ix_cloud_model_user_task", table_name="cloud_provider_models")
    op.drop_table("cloud_provider_models")
    op.drop_index("ix_perm_user", table_name="camera_permissions")
    op.drop_index("ix_perm_camera", table_name="camera_permissions")
    op.drop_index(
        op.f("ix_camera_permissions_user_id"), table_name="camera_permissions"
    )
    op.drop_index(op.f("ix_camera_permissions_id"), table_name="camera_permissions")
    op.drop_index(
        op.f("ix_camera_permissions_camera_id"), table_name="camera_permissions"
    )
    op.drop_table("camera_permissions")
    op.drop_index(op.f("ix_camera_configs_id"), table_name="camera_configs")
    op.drop_table("camera_configs")
    op.drop_index(op.f("ix_tenant_quotas_id"), table_name="tenant_quotas")
    op.drop_table("tenant_quotas")
    op.drop_index(
        op.f("ix_cloud_provider_credentials_user_id"),
        table_name="cloud_provider_credentials",
    )
    op.drop_index(
        op.f("ix_cloud_provider_credentials_token_hash"),
        table_name="cloud_provider_credentials",
    )
    op.drop_index(
        op.f("ix_cloud_provider_credentials_provider"),
        table_name="cloud_provider_credentials",
    )
    op.drop_index(
        "ix_cloud_cred_user_provider", table_name="cloud_provider_credentials"
    )
    op.drop_table("cloud_provider_credentials")
    op.drop_index(op.f("ix_cameras_id"), table_name="cameras")
    op.drop_index("ix_camera_owner", table_name="cameras")
    op.drop_index("ix_camera_ip", table_name="cameras")
    op.drop_table("cameras")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_timestamp"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index("ix_role_permissions_role", table_name="role_permissions")
    op.drop_index("ix_role_permissions_perm", table_name="role_permissions")
    op.drop_index(op.f("ix_role_permissions_id"), table_name="role_permissions")
    op.drop_table("role_permissions")
    op.drop_index(
        op.f("ix_ai_detection_results_task"), table_name="ai_detection_results"
    )
    op.drop_index(
        op.f("ix_ai_detection_results_model_id"), table_name="ai_detection_results"
    )
    op.drop_index(op.f("ix_ai_detection_results_id"), table_name="ai_detection_results")
    op.drop_index(
        op.f("ix_ai_detection_results_created_at"), table_name="ai_detection_results"
    )
    op.drop_index(
        op.f("ix_ai_detection_results_camera_id"), table_name="ai_detection_results"
    )
    op.drop_table("ai_detection_results")
    op.drop_index(op.f("ix_security_settings_key"), table_name="security_settings")
    op.drop_index(op.f("ix_security_settings_id"), table_name="security_settings")
    op.drop_table("security_settings")
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.drop_index(op.f("ix_roles_id"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_permissions_name"), table_name="permissions")
    op.drop_index(op.f("ix_permissions_id"), table_name="permissions")
    op.drop_table("permissions")
    op.drop_index(op.f("ix_password_policy_id"), table_name="password_policy")
    op.drop_table("password_policy")
    op.drop_index(op.f("ix_integrations_id"), table_name="integrations")
    op.drop_table("integrations")
    op.drop_index(op.f("ix_firewall_rules_id"), table_name="firewall_rules")
    op.drop_table("firewall_rules")
    op.drop_index(op.f("ix_ai_models_task"), table_name="ai_models")
    op.drop_index(op.f("ix_ai_models_source_type"), table_name="ai_models")
    op.drop_index(op.f("ix_ai_models_id"), table_name="ai_models")
    op.drop_index(op.f("ix_ai_models_assigned_camera_id"), table_name="ai_models")
    op.drop_table("ai_models")
    # ### end Alembic commands ###
