#!/usr/bin/env python3
# Copyright (c) 2026 OpenNVR
# SPDX-License-Identifier: Apache-2.0
"""Generate the site's derived pages.

Two things, both derived so they cannot rot:

* ``docs_src/reference/<tier>.md`` — one page per
  ``opennvr_app_sdk.API_TIERS`` entry, one ``:::`` block per export, in
  the tier's own order. A name added to a tier appears on the site
  without anyone remembering to add it, and a name removed cannot leave
  a dead page behind.
* ``docs_src/cookbook.md`` — the cookbook index, with its
  repository-relative links rewritten to GitHub so they resolve for a
  reader on the published site.

    python scripts/gen_reference.py            # write docs_src/reference/
    python scripts/gen_reference.py --check    # fail if it would change
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from opennvr_app_sdk import API_TIERS  # noqa: E402

#: Where cookbook files live once published.
COOKBOOK_URL = (
    "https://github.com/open-nvr/open-nvr/blob/main/sdk/opennvr-app-sdk/cookbook/"
)

#: Tier slug → (page title, the lede that opens the page).
PAGE_TEXT: dict[str, tuple[str, str]] = {
    "front-door": (
        "Front door",
        "Six names. If you are writing your first app, this is the whole\n"
        "API — `App` declares it, `@app.on_detection` is the rule, and\n"
        "`event.alert()` is what reaches an operator. Everything else on\n"
        "this site is for the app that outgrows them.",
    ),
    "archetypes": (
        "Archetypes",
        "The classes `App` compiles to. Subclass one directly when the\n"
        "decorators stop fitting — several interacting state machines, a\n"
        "custom event walk, or a rule that needs the whole detection\n"
        "batch at once. Same process, same manifest, same alerts.",
    ),
    "rules": (
        "Writing a rule",
        "Where the object is, how long it has been there, and what to fire\n"
        "when it matters. Most rules are a zone, a dwell timer and an\n"
        "alert; these are those three, unwrapped.",
    ),
    "platform": (
        "The platform",
        "Everything an app reads from the running deployment: the camera\n"
        "roster it was assigned, snapshots, recordings, the timeline and\n"
        "its evidence, durable state, and inference. The app's own\n"
        "credential scopes all of it — an app cannot see the whole site by\n"
        "accident.",
    ),
    "surfaces": (
        "App surfaces",
        "What the app exposes back. Declare a state view or an action and\n"
        "the App Catalog renders it with no frontend of yours; declare a\n"
        "licence gate and core will not enable the app until your code\n"
        "says the key is good.",
    ),
    "events": (
        "The event bus",
        "Contracted domain events are how one app becomes another app's\n"
        "input — versioned in the subject, defined in EVENT_CONTRACTS.md,\n"
        "typed here. Tier-0 is the always-on detector every camera already\n"
        "runs, free to consume.",
    ),
    "config": (
        "Config helpers",
        "The file-loading edge, for a loader that does its own parsing.\n"
        "Most apps want `BaseAppConfig` and `load_app_config` instead.",
    ),
}


def page(slug: str, names: tuple[str, ...]) -> str:
    title, lede = PAGE_TEXT[slug]
    out = [
        "<!-- Generated by scripts/gen_reference.py — do not edit. -->",
        f"# {title}",
        "",
        lede,
        "",
    ]
    for name in names:
        # No hand-written heading: mkdocstrings renders the symbol's own
        # (with its type and a stable anchor) at heading_level 2.
        out += [f"::: opennvr_app_sdk.{name}", ""]
    return "\n".join(out).rstrip() + "\n"


COOKBOOK_HEADER = """<!-- Generated by scripts/gen_reference.py from cookbook/README.md — do not edit. -->
# Cookbook

One runnable file per class — how it is constructed or subclassed, and
which APIs it uses. Every file is imported and exercised by the SDK's
test suite, so an example that references a name the SDK no longer
exports breaks in CI rather than misleading you months later.

"""


def cookbook_page(readme: str) -> str:
    """The cookbook index with its links pointed at GitHub."""
    body = readme.split("\n", 1)[1] if readme.startswith("# ") else readme
    # Drop the README's own lede; COOKBOOK_HEADER replaces it.
    marker = "## Write an app"
    body = body[body.index(marker):] if marker in body else body.lstrip()
    body = re.sub(r"\]\((\d\d_[a-z0-9_]+\.py)\)", rf"]({COOKBOOK_URL}\1)", body)
    return COOKBOOK_HEADER + body.rstrip() + "\n"


def write(path: Path, body: str, *, check: bool) -> bool:
    """Write ``body`` unless ``check``; returns True when it differed."""
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current == body:
        return False
    if not check:
        path.write_text(body, encoding="utf-8")
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if any page would change")
    args = parser.parse_args(argv)

    target = ROOT / "docs_src" / "reference"
    target.mkdir(parents=True, exist_ok=True)
    stale = False
    written = []
    for slug, names in API_TIERS.items():
        path = target / f"{slug}.md"
        stale |= write(path, page(slug, names), check=args.check)
        written.append(path.name)

    stale |= write(
        ROOT / "docs_src" / "cookbook.md",
        cookbook_page((ROOT / "cookbook" / "README.md").read_text(encoding="utf-8")),
        check=args.check,
    )

    for orphan in target.glob("*.md"):
        if orphan.name not in written:
            stale = True
            if not args.check:
                orphan.unlink()

    if args.check and stale:
        print("reference pages are out of date — run "
              "`python scripts/gen_reference.py`", file=sys.stderr)
        return 1
    if not args.check:
        print(f"wrote {len(written)} reference pages to {target} + cookbook.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
